export const UI_ADD_TRANSACTION = 'UI_ADD_TRANSACTION'
export const UI_REMOVE_TRANSACTION = 'UI_REMOVE_TRANSACTION'

export const ADD_QUOTE = 'ADD_QUOTE'
export const REMOVE_QUOTE = 'REMOVE_QUOTE'
export const UPDATE_QUOTE_SUCCEEDED = 'UPDATE_QUOTE_SUCCEEDED'
export const UPDATE_QUOTE_ERROR = 'UPDATE_QUOTE_ERROR'

export const SUBSCRIBE_SYMBOL = 'SUBSCRIBE_SYMBOL'
export const UNSUBSCRIBE_SYMBOL = 'UNSUBSCRIBE_SYMBOL'

export const PORTFOLIO_LOADED = 'PORTFOLIO_LOADED'
export const PORTFOLIO_ADD_TRANSACTION = 'PORTFOLIO_ADD_TRANSACTION'
export const PORTFOLIO_REMOVE_TRANSACTION = 'PORTFOLIO_REMOVE_TRANSACTION'
